# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac56e1f37835cc80e87cf0b3acfba064f8cb6ae35764bb782370bd99ae8eeb55c80ecc7c02df75303bf5c8c2bba90d4aaf06f7cd89ba74bbe8dbcf15bd1e4532

test:
  secret_key_base: 8a407d5f019a31dd545a8f98f3c627991eb40e5490658ef4fb1d8aa33f156922e6c85865e719e33a548b5e2b20d43033e9532bd25775228b792586c6dc5077ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
